# Generated by Django 3.0.6 on 2020-05-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_auto_20200521_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='image',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
